apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-service
  labels:
    app: employee-service
spec:
  # ClusterIP = internal only (within cluster)
  # Use LoadBalancer if you want direct external access (cloud only)
  type: ClusterIP

  selector:
    app: employee-service   # routes traffic to pods with this label

  ports:
    - name: http
      protocol: TCP
      port: 80          # port the Service listens on
      targetPort: 8080  # port on the pod (matches containerPort in deployment)